version: 0.0
os: linux
files:
  - source: /appspec.yaml
    destination: /home/
    overwrite: true

permissions:
  - object: /home/
    pattern: "**"
    owner: root
    group: root
    mode: 775
    type:
      - directory
      - file

hooks:
  BeforeInstall:

  AfterInstall:

  ApplicationStop:
