version: 0.2

phases:
  build:
    commands:
       - npm install --legacy-peer-deps
       - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  secondary-artifacts:
    artifact1:
      files:
        - appspec.yml
    
