version: 0.2

phases:
  build:
    commands:
       - npm install --legacy-peer-deps
       - npm run build
artifacts:
  files:
    - appspec.yml
  discard-paths: yes  
  secondary-artifacts:
    artifact1:
      files:
        - '**/*'
      base-directory: 'build' 
      discard-paths: yes
    
