version: 0.2

phases:
  build:
    commands:
       - npm install --legacy-peer-deps
       - npm run build
  post_build:
     commands:
        - cp -r appspec.yml build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
